### PR TITLE
Add step function in RollingPinEnv

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)

### CODE REVIEW

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-:-NIoT8og1q5CuF5IpdBS:bg7igkv)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 320 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQtBS0Ll3E6gHqqu0:-NIoQtBS0Ll3E6gHqqu1:b6nipf7) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L320)):*
> ```Python
>         return (np.abs(R_Wpin[2, 1]) <= tol)
> 
>     def step(self, action: np.ndarray) -> None:
> ```

btw do you have a pros/cons list comparing this action formulation against alternatives?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 352 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQCQS0ZBjZWIZNcQF:-NIoQCQS0ZBjZWIZNcQG:b-krd0m6) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L352)):*
> ```Python
>         # delta yaw angle.
>         if delta_yaw == 0.:
>             # Now turning, move a straight line along pin's y axis.
> ```

btw think this is a typo `Now` -> `No`?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 320 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQtBS0Ll3E6gHqqu0:-NIs0C7K42X_5O-paEh6:b-bgyyjn) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L320)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw do you have a pros/cons list comparing this action formulation against alternatives?
</blockquote></details>

I have considered these action options
1. duration, rolling_distance, delta_height, delta_yaw, delta_pitch
2. duration, delta pose (pose is in SE(3), including the 3-dimensional position and orientation).

I think this choice is better than the delta pose, for two reasons
1. It doesn't make too much sense to move the rolling pin in the direction parallel to the pin axis, that would cause a lot of sliding friction between the rolling pin and the dough. Instead we want to move the rolling pin in the direction perpendicular to the pin axis in the horizontal plane. Hence we know the direction of the rolling pin motion at each instance in time, we then only need to specify the distance of the motion.
2. The orientation has 3 components, but due to the symmetry of the rolling pin capsule, one orientation component doesn't matter (the rotation angle about the axis of the rolling pin), hence we only need to specify two components of the orientation (delta_yaw and delta_pitch).

Would you suggest some alternative actions?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 352 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQCQS0ZBjZWIZNcQF:-NIs2ytd4-JUuCy6P4Fm:b-896fix) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L352)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw think this is a typo `Now` -> `No`?
</blockquote></details>

Done.

**Review by blake-wulfe-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 320 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQtBS0Ll3E6gHqqu0:-NIsZzhj9DxyLr6SMHbH:b2dozd1) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L320)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I have considered these action options
1. duration, rolling_distance, delta_height, delta_yaw, delta_pitch
2. duration, delta pose (pose is in SE(3), including the 3-dimensional position and orientation).

I think this choice is better than the delta pose, for two reasons
1. It doesn't make too much sense to move the rolling pin in the direction parallel to the pin axis, that would cause a lot of sliding friction between the rolling pin and the dough. Instead we want to move the rolling pin in the direction perpendicular to the pin axis in the horizontal plane. Hence we know the direction of the rolling pin motion at each instance in time, we then only need to specify the distance of the motion.
2. The orientation has 3 components, but due to the symmetry of the rolling pin capsule, one orientation component doesn't matter (the rotation angle about the axis of the rolling pin), hence we only need to specify two components of the orientation (delta_yaw and delta_pitch).

Would you suggest some alternative actions?
</blockquote></details>

Ok, that makes sense, and I think it makes sense to start with this, but I'll elaborate a bit below for future reference.

I was wondering if an absolute action space (relative to the task reference frame) as opposed to an action space that's relative to the current pose of the rolling pin might have some advantages (RoboCraft does that for example). 

It seems like there are a few options for how to do that. One would be (starting pose, end pose) (maybe constraining certain things to match between them). Another would be similar to what you have here (starting pose, duration, rolling_distance, ...).

Advantages:
1. The model doesn’t need to know / account for the current state of the rolling pin. Of course, we could provide this to it by e.g., concatenating the current state to intermediate layer outputs, but learning to account for that might be less sample efficient.
2. If it’s necessary to reposition the rolling pin (without touching the dough), the model doesn’t need to sample the action to do the repositioning, it can just directly output the next start state.
3. There might be less variation in the “position” of the dough than of the rolling pin, so accounting for the shifts of the dough as opposed to the shifts in position of the rolling pin might be more sample efficient. 
4. Covariate shift (of the model-based variety) might be less of an issue. E.g., with the relative action space you might sample an action slightly out of distribution, resulting in a rolling pin state that's slightly out of distribution, which when input to the model might give worse next state prediction results, etc. Whereas if you output the start state of the rolling pin each time, maybe you build in a recovery mechanism. I'm not sure how much of a problem this is in practice.

Disadvantages:
1. Larger action space to have to search over
2. Planner might output starting poses that are quite different from the current pose, which might make the overall trajectories slow
3. If you move the dough position around the task space, then you’ll need to learn to account for that with the absolute actions
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 335 at r2](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIsgZ7I5ec8hTvGexzJ:-NIsgZ7I5ec8hTvGexzK:b4251we) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/dabab935076afb320953c24767fce4b6055c0e39/mani_skill2/envs/mpm/rolling_env.py#L335)):*
> ```Python
>         starting pose to the final pose.
>         """
>         duration, rolling_distance, delta_height, delta_yaw, delta_pitch = \
> ```

btw you should be able to just do 
```python
duration, rolling_distance, delta_height, delta_yaw, delta_pitch = action
```



_Code quote:_
```Python
        duration, rolling_distance, delta_height, delta_yaw, delta_pitch = \
            action[0],  action[1], action[2], action[3], action[4]
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 335 at r2](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIsgZ7I5ec8hTvGexzJ:-NItYWc96m6-Nr7Jbdla:bfc973w) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/dabab935076afb320953c24767fce4b6055c0e39/mani_skill2/envs/mpm/rolling_env.py#L335)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw you should be able to just do 
```python
duration, rolling_distance, delta_height, delta_yaw, delta_pitch = action
```
</blockquote></details>

Done, neat!

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 320 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQtBS0Ll3E6gHqqu0:-NItlnw-AF65ovPOGjMx:b7ygy4) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L320)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, I also started to implement `step()` function by using the absolute pose (including the starting pose), but then shifted to the relative pose. The reason is that in order to use the (starting pose, ending pose) action space, we need to do the following steps
1. Move the rolling pin to the starting pose
2. Move the rolling pin to the ending pose.

We could accomplish this by calling the current `step` function for twice. Namely the current `step` function is a building block, if we later switch to a different action space.

What do you think if I rename this function to `step_relative`, and we define an option on the action space
```py
enum class ActionOption {
  RELATIVE,
  ABSOLUTE,
}
```

and we then implement `step_relative()` and `step_absolute()` function respectively. Then in the `step` function we choose to call `step_relative()` or `step_absolute()` based on the ActionOption. This will allow a rich set of action spaces.
</blockquote></details>

got it, yeah that sounds good!

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 320 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/3#-NIoQtBS0Ll3E6gHqqu0:-NJ7QHkKBIJfFUd-jFv-:biwnqc3) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/4588744145b4191c14c57081a05e61f116c16838/mani_skill2/envs/mpm/rolling_env.py#L320)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

got it, yeah that sounds good!
</blockquote></details>

Done.

Sorry for the delay. I was working on some other research project over the weekend.

**Pull request merged**
