### PR TITLE
Add modeling and training code

### PR DESCRIPTION
**Pull request by blake-wulfe-tri**
This PR combines two commits.

The first commit defines a DynamicsModel base class
along with a network (a U-net), and a DynamicsModel
subclass that wraps a network.

The second commit adds pytorch lightning code 
(a module for training DynamicsModels), and the
script and config used to train the models.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12)

### CODE REVIEW

**Review by blake-wulfe-tri — COMMENTED** [review]
+@hongkai-dai Ok I just combined the two. This is sort of huge sorry about that. A fair amount of code is copied from an old project of mine (the data loading code).

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NNskNpr2VQv9cUmFnxX:b-a0ot3v)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Checkpoint. Sorry I think I will need some time to review this PR, as I am not familiar with some of the tools (FiLM, ray.rllib or pytorch_lightening, I would like to learn these tools first and then review the PR).

> Reviewed 5 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NNu4IOmBcFsucs0mW7H:b-hfuci1)* status: 5 of 19 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 703 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NNu3K1N52if_dofe-er:-NNu3K1N52if_dofe-es:byyybho) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/d298b8b1a2e33e6e73f978a82bb8c58d1675ad3a/mani_skill2/envs/mpm/rolling_env.py#L703)):*
> ```Python
>         return np.mean(particle_q, axis=0)
> 
>     def _get_obs(self):
> ```

Could you document here that the observation dimension is 1 x grid_size_x x grid_size_y? I think the extra channel is sort of unexpected and hence worth mentioning in the doc.

**Review by blake-wulfe-tri — COMMENTED** [review]
No rush! I'm also happy to give a crash course if that'd be helpful. Thanks for reviewing some much code at once.
Also I'm making heavy use of a library called [hydra](https://github.com/facebookresearch/hydra) for configs / training (similar in some ways to the config system they have in Anzu).

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NNvx9HCB3TmsKQHrpU0:beq9xp6)* status: 5 of 19 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by blake-wulfe-tri — COMMENTED** [review]
oh actually it's possible you are already familiar with it

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NNvy0ki0Ivr9vMhJyli:by20wco)* status: 5 of 19 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 703 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NNu3K1N52if_dofe-er:-NNw3bGm0j9iNX1gE-gD:b-mwbb8v) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/d298b8b1a2e33e6e73f978a82bb8c58d1675ad3a/mani_skill2/envs/mpm/rolling_env.py#L703)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document here that the observation dimension is 1 x grid_size_x x grid_size_y? I think the extra channel is sort of unexpected and hence worth mentioning in the doc.
</blockquote></details>

actually this is not a good way to do it. I changed this back to (height, width) and addressed the issue in the model instead

**Review by hongkai-dai — COMMENTED** [review]
Sorry for the late reply. I have been working on other PRs in the last two days, and just got to this PR.

BTW, which version of ray.rllib do you install? The most recent version 2.2.0 requires gym-0.23, but ManiSkill2 requires gym <= 0.21.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NO399Z66aDehn0wdlzD:bpmoknb)* status: 3 of 19 files reviewed, 1 unresolved discussion

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Checkpoint.

Sorry for the super slow review. There are a lot of things I need to learn. I only used simple MLP in my previous research.

> Reviewed 3 of 19 files at r1, 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NO8_9-D2zKKR2qbHt0X:b-a7yzbc)* status: 11 of 19 files reviewed, 5 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/dynamics/networks.py` line 70 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO60XfQ2GJiRMsBN2JR:-NO60XfR-86T1hp5wZMf:b-rsaqr4) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L70)):*
> ```Python
> 
>             def forward(self, x, gamma, beta):
>                 x = self.conv1(x)
> ```

Sorry for the naive question, but why do we have `bn1` here? In the FiLM paper, figure 3, it goes as conv-> relu -> conv -> bn -> film -> relu, namely it only has one batch normalization after the second convolution, where the first convolution output goes to the relu directly.

What we implement seems to be the unet double conv https://github.com/milesial/Pytorch-UNet/blob/67bf11b4db4c5f2891bd7e8e7f58bcde8ee2d2db/unet/unet_parts.py, add we add a FiLM layer just before the final relu.
___
*[`mani_skill2/dynamics/networks.py` line 90 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8M7G-6FGkWh04FV6A:-NO8M7G-6FGkWh04FV6B:b2p4jia) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L90)):*
> ```Python
>                 return x
> 
>         class up(nn.Module):
> ```

Should it be `Up` (with upper case `U`) here?
___
*[`mani_skill2/dynamics/networks.py` line 100 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8MBOVA9VvvRLRVbwD:-NO8MBOVA9VvvRLRVbwE:b7jttev) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L100)):*
> ```Python
>                 else:
>                     self.up = nn.ConvTranpose2d(
>                         in_channels // 2, in_channels // 2, kernel_size=2, stride=2
> ```

Sorry I don't get why the first in_channels should divide by 2 here.
___
*[`mani_skill2/dynamics/networks.py` line 128 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8QWj06eJvssnwZ613:-NO8QWj06eJvssnwZ614:bliwgz2) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L128)):*
> ```Python
>         self.down2 = DownFiLM(128, 256)
>         self.down3 = DownFiLM(256, 512)
>         self.down4 = DownFiLM(512, 512)
> ```

Seems to me that it the output channel is 512 if bilinear = True (which is the default value), but if bilinear is false, then the output channel should be 1024?
___
*[`mani_skill2/dynamics/networks.py` line 136 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8OrgV6aV9OodFdxFx:-NO8OrgV6aV9OodFdxFy:b-sy4j01) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L136)):*
> ```Python
> 
>         n_film_parameters = (128 + 256 + 512 + 512) * 2
>         self.film_generator = nn.Linear(self.cond_size, n_film_parameters)
> ```

Just curious, why we use gamma and beta as linear function of `cond`?

**Review by blake-wulfe-tri — COMMENTED** [review]
Good catch. I just did `pip install ray[rllib]` so probably it's a conflicting gym version and I need to be explicit in the environment file

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NOANqu5-nt9V6EPzqKF:b-utvyyp)* status: 11 of 19 files reviewed, 5 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/dynamics/networks.py` line 70 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO60XfQ2GJiRMsBN2JR:-NOAHyNyDV3qld4idr00:bouxy5b) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry for the naive question, but why do we have `bn1` here? In the FiLM paper, figure 3, it goes as conv-> relu -> conv -> bn -> film -> relu, namely it only has one batch normalization after the second convolution, where the first convolution output goes to the relu directly.

What we implement seems to be the unet double conv https://github.com/milesial/Pytorch-UNet/blob/67bf11b4db4c5f2891bd7e8e7f58bcde8ee2d2db/unet/unet_parts.py, add we add a FiLM layer just before the final relu.
</blockquote></details>

I basically just copied the code from here "https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_parts.py" (referenced it in the class doc, but maybe should have been more explicit), and then added in the FiLM layers. The short answer is probably that it doesn't matter much, though.
___
*[`mani_skill2/dynamics/networks.py` line 90 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8M7G-6FGkWh04FV6A:-NOAKCPp5ZkAcMBcF2VW:bd8h1yu) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L90)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should it be `Up` (with upper case `U`) here?
</blockquote></details>

Again just copied this, but I guess you're right. I changed the other one to `DownFiLM` so this should be capitalized. I'm going to wait for more comments to make changes, though.
___
*[`mani_skill2/dynamics/networks.py` line 100 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8MBOVA9VvvRLRVbwD:-NOALnB8CpcWQNS4xMWN:b-r0k3xm) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't get why the first in_channels should divide by 2 here.
</blockquote></details>

(again, copied this code so not 100%) I think `in_channels` here refers to the number of channels input into the `self.conv` layer. Since that's the concatenation of `x1` and `x2` below (which each have in_channels // 2 channels), this divides the provided `in_channels` by two. In other words, `self.up` is only applied to have the channels / the first input to `forward`.
___
*[`mani_skill2/dynamics/networks.py` line 128 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8QWj06eJvssnwZ613:-NOANHKl1Df-9MBgHOt1:b-pz92fl) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L128)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Seems to me that it the output channel is 512 if bilinear = True (which is the default value), but if bilinear is false, then the output channel should be 1024?
</blockquote></details>

Short answer: I think I should remove the `ConvTranspose2d` option (i.e., always use the bilinear upsampling)
___
*[`mani_skill2/dynamics/networks.py` line 136 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8OrgV6aV9OodFdxFx:-NOANa6yAzEDzier48YS:b-6oikx5) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L136)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious, why we use gamma and beta as linear function of `cond`?
</blockquote></details>

I tried to use multiple layers originally and it didn't work, but I didn't try that hard. I should probably just parameterize the number of layers used for the generator.

**Review by blake-wulfe-tri — COMMENTED** [review]
No problem! thanks for taking the time to look into the tools. 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NOGwgq581Biv-EMIdZ3:b5ge08c)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/dynamics/networks.py` line 70 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO60XfQ2GJiRMsBN2JR:-NOGwRjhDO_6Ou04aJyC:b-896fix) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Got it, thanks for the explanation.
</blockquote></details>

Done.
___
*[`mani_skill2/utils/testing/rllib_test_utils.py` line 27 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NODhtI9EfoqgEt8_Y1K:-NOGwauQA16xU85maHK7:bxsnlq) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/utils/testing/rllib_test_utils.py#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For my own education, why using this list comprehension instead of `rewards = [0] * batch_size`?
</blockquote></details>

I suspect I was just being consistent with the other list comprehensions so it was easier to read

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/dynamics/networks.py` line 90 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8M7G-6FGkWh04FV6A:-NOHAChr6s5FeM2D2UhH:bb7f2mf) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L90)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

Again just copied this, but I guess you're right. I changed the other one to `DownFiLM` so this should be capitalized. I'm going to wait for more comments to make changes, though.
</blockquote></details>

done
___
*[`mani_skill2/dynamics/networks.py` line 100 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8MBOVA9VvvRLRVbwD:-NOHBcVp7pSU-Dy5cKPJ:bw5m363) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The original code https://github.com/milesial/Pytorch-UNet/blob/40d5ba797c5689cd9560233baa0e52f28f92727c/unet/unet_parts.py#L53 uses `in_channels` (without dividing by 2).

> ince that's the concatenation of x1 and x2 below (which each have in_channels // 2 channels), this divides the provided in_channels by two. In other words, self.up is only applied to have the channels / the first input to forward

That makes sense, but now I am confused. Here self.up(x1) is applied on `x1`, which only has half of the channels as in `in_channels`.
</blockquote></details>

Again, I'll avoid the issue b/c I don't actually understand it, and just say I'll remove the ConvTranspose stuff. (I should probably go through and understand, but just rushing a little)
___
*[`mani_skill2/dynamics/networks.py` line 128 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8QWj06eJvssnwZ613:-NOHAg1ECnkHDYr2AFW7:b-896fix) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L128)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Done.
___
*[`mani_skill2/dynamics/networks.py` line 136 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NO8OrgV6aV9OodFdxFx:-NOHAhyj7GTLLKglY_EF:b-49i3g9) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/dynamics/networks.py#L136)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Got it. If the simple linear gamma/beta function works, then I think that is better than using a more complicated function.
</blockquote></details>

Yeah I agree with that. It's hard to say (a) whether we will need more layers (b) if it turns out that we need whether it will be easily learnable. I'll leave it for now
___
*[`mani_skill2/utils/testing/rllib_test_utils.py` line 27 at r2](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-NODhtI9EfoqgEt8_Y1K:-NOHAuwhBLGWlKE25hnG:b-896fix) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/5eb3833fa76bd68437806feb7d330d802dbc466b/mani_skill2/utils/testing/rllib_test_utils.py#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, makes sense.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12#-:-NOHQKgb73IqL0paO2qo:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @blake-wulfe-tri)

**Review by hongkai-dai — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Pull request merged**
