### PR TITLE
Add a function to generate state_action tuple data for dough rolling.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/5)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-:-NJm99uI7JU6_CgkNMTa:b9e17as)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-:-NJmqZ56EKPZF7VUEbGX:bg7igkv)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`examples/dough_model_learning/data_generation.py` line 93 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-NJmpNMLEyuBGgk3j898:-NJmpNMLEyuBGgk3j899:b-50mps3) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/5864950ecbcd2b356c96d3a24d881e5c32200a0a/examples/dough_model_learning/data_generation.py#L93)):*
> ```Python
> 
> @dataclass
> class StateActionPair:
> ```

btw if you include the next_state in this class then it's not really a (state, action) pair. Might consider calling this `Transition` or `DynamicsTransition` or `TransitionTuple` or similar
___
*[`examples/dough_model_learning/data_generation.py` line 106 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-NJmq1mD9pBnAB6m16Xr:-NJmq1mD9pBnAB6m16Xs:bq6znyj) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/5864950ecbcd2b356c96d3a24d881e5c32200a0a/examples/dough_model_learning/data_generation.py#L106)):*
> ```Python
> 
> 
> def generate_state_action_pair(
> ```

btw this is interesting. I assume you intend to use this to generate data? If so how do you plan on chaining calls to this function together (if at all)? Would it make more sense to generate data via full rollouts / trajectories?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/5)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`examples/dough_model_learning/data_generation.py` line 93 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-NJmpNMLEyuBGgk3j898:-NJnODr3Cg5H3gzWCRKI:b-oyxfna) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/5864950ecbcd2b356c96d3a24d881e5c32200a0a/examples/dough_model_learning/data_generation.py#L93)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw if you include the next_state in this class then it's not really a (state, action) pair. Might consider calling this `Transition` or `DynamicsTransition` or `TransitionTuple` or similar
</blockquote></details>

Done. I changed to `TransitionTuple`.
___
*[`examples/dough_model_learning/data_generation.py` line 106 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-NJmq1mD9pBnAB6m16Xr:-NJnOHST7Z5r1wFDn9WW:bs70791) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/5864950ecbcd2b356c96d3a24d881e5c32200a0a/examples/dough_model_learning/data_generation.py#L106)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw this is interesting. I assume you intend to use this to generate data? If so how do you plan on chaining calls to this function together (if at all)? Would it make more sense to generate data via full rollouts / trajectories?
</blockquote></details>

I haven't thought much about chaining calls yet. I was thinking about generating (current_state, action, next_state) in independent calls as a first step, as currently I don't have roll out yet.

The downside of arbitrarily sample current_state and action, is that we get a lot of  useless transition tuples, that won't appear when we roll out our actual policy. So I was thinking about interleaving the model learning and planning, that after we learned a model, we then use this learned model to plan certain actions to the a variety of goal states, and then roll out these planned actions, then refine our model with these roll outs. Does this make sense to you?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/5)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`examples/dough_model_learning/data_generation.py` line 106 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/5#-NJmq1mD9pBnAB6m16Xr:-NJnTPqEA97klXBs0Ehv:b-uwkowd) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/5864950ecbcd2b356c96d3a24d881e5c32200a0a/examples/dough_model_learning/data_generation.py#L106)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I haven't thought much about chaining calls yet. I was thinking about generating (current_state, action, next_state) in independent calls as a first step, as currently I don't have roll out yet.

The downside of arbitrarily sample current_state and action, is that we get a lot of  useless transition tuples, that won't appear when we roll out our actual policy. So I was thinking about interleaving the model learning and planning, that after we learned a model, we then use this learned model to plan certain actions to the a variety of goal states, and then roll out these planned actions, then refine our model with these roll outs. Does this make sense to you?
</blockquote></details>

:lgtm_strong:

**Pull request merged**
