### PR TITLE
Add rolling pin

### PR DESCRIPTION
**Pull request by hongkai-dai**
This PR adds a simulation environment `rolling_env.py`.

The main feature is that the robot (rolling pin) is not an "articulation" (robot with revolute/prismatic joint under PD control), but a free-floating single rigid body. We apply a wrench on this rolling pin directly.

Currently the dough seems quite stiff. It doesn't deform much under the pressure of the rolling pin. This could be because that the rolling pin controller is not stiff enough.

In the next PR I will try one-way coupling, that the rolling pin just follows a prescribed trajectory.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NIADAzvBwCPEuSt_7uu:b9e17as)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
before I review: 
1. how strict do you want to be about e.g., style / formatting / comments?
2. should we follow a particular style guide e.g., https://google.github.io/styleguide/pyguide.html
3. how much testing do we want to require (e.g., how much testing do we want there to be for this env or the controllers as an example)?

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NIBOB6Y0wcTzBeYI3wM:b9x3ii3)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by hongkai-dai** [comment]
I am following the anzu repo convention. In anzu we often write code as quickly as possible, with partial test coverage.
1. Currently I am using `yapf` to reformat the code, would you recommend some other tools?
2. I haven't used google's python coding style, but that looks great. Let's enforce it here. 
3. Anzu only has partial test coverage. How about we add tests if the new code is a "library", meaning it will be used as a utility function by several other code. For other code that are "application", we don't require tests. Does this sound good to you?

**Review by blake-wulfe-tri — COMMENTED** [review]
1. yapf works for me
2. sounds good
3. sounds good

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NIEXy1zE9GumJhQZ2gQ:bn03vf4)* status: 0 of 3 files reviewed, all discussions resolved

**Review by blake-wulfe-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @hongkai-dai)

___
*[`examples/demo_rolling.py` line 4 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEYbJD2fELO0o8dpvy:-NIEYbJD2fELO0o8dpvz:bfbxtw1) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L4)):*
> ```Python
> import numpy as np
> 
> from mani_skill2.envs.sapien_env import BaseEnv
> ```

btw technically imports should be lexicographically ordered https://google.github.io/styleguide/pyguide.html#313-imports-formatting
(if these comments are too particular we can drop it, but I think this one is sort of helpful)
___
*[`examples/demo_rolling.py` line 11 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEY7-HEgF_kLEyA-bL:-NIEY7-HEgF_kLEyA-bM:b-7mrqt6) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L11)):*
> ```Python
> def main():
>     #env: BaseEnv = gym.make("Rolling-v0", control_mode="pd_ee_delta_pose")
>     sim_freq = 500
> ```

btw technically these should be constants in caps at the top https://google.github.io/styleguide/pyguide.html#3164-guidelines-derived-from-guidos-recommendations
___
*[`examples/demo_rolling.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEZ56a23YFNX9THDHO:-NIEZ56a23YFNX9THDHP:brjn264) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L39)):*
> ```Python
>         if after_reset:
>             after_reset = False
>             # Re-focus on opencv viewer
> ```

btw technically comments should end in an period / have punctation. (this one probably too annoying)
https://google.github.io/styleguide/pyguide.html#385-block-and-inline-comments
___
*[`examples/demo_rolling.py` line 46 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEZH9xAaGu0nE8uqdf:-NIEZH9xAaGu0nE8uqdg:bv67guy) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L46)):*
> ```Python
> 
>         action = env.agent.robot.get_pose().p
>         # Position
> ```

btw what's this doing?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEZUETDpII9EnJz3gk:-NIEZUETDpII9EnJz3gl:busc8ov) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L10)):*
> ```Python
> from mani_skill2.agents.base_agent import BaseAgent
> from mani_skill2.agents.configs.rolling_pin import defaults
> from ..camera import MountedCameraConfig, get_camera_images, get_camera_pcd
> ```

btw technically shouldn't use relative imports https://google.github.io/styleguide/pyguide.html#22-imports
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 14 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEZcNA1KzGKxciKPVO:-NIEZcNA1KzGKxciKPVP:b-gpelol) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L14)):*
> ```Python
> 
> class RollingPinPositionController:
>     """
> ```

btw technically comment should begin on first docstring line https://google.github.io/styleguide/pyguide.html#382-modules
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 20 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEauiR2ppmeIyr_uTK:-NIEauiS2VgLLfAF-CTX:b-6o0gg6) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L20)):*
> ```Python
>     This is a "placeholder" controller to test the API.
>     """
>     pin: sapien.Actor
> ```

maybe missing something, but what's the purpose of these?



_Code quote:_
```Python
    pin: sapien.Actor
    gravity: np.ndarray
    Kp: float
    Kd: float
```

**Review by blake-wulfe-tri — COMMENTED** [review]
- Did a full pass; looks great!
- Left a lot of comments, but I think all are just suggestions really
- I haven't run it on my puget yet. 

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NIFoIfOCiDQ5MDLXIAh:b-mcf1bk)* status: 0 of 3 files reviewed, 24 unresolved discussions (waiting on @hongkai-dai)

___
*[`examples/demo_rolling.py` line 47 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFjKhvBLGCG-5I66ur:-NIFjKhvBLGCG-5I66us:bf0s93a) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L47)):*
> ```Python
>         action = env.agent.robot.get_pose().p
>         # Position
>         if key == "i":  # +x
> ```

btw alternative way to do this would be to use a map like:
```python
KEY_TO_ACTION_MAP = {
  "i": [EE_ACTION, 0, 0],
...
}

# Then in this for loop:
if key == "q":
  break
action += KEY_TO_ACTION_MAP[key]
```

Is that better? Maybe slightly
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 32 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFkb6s0L_z97mzdrcb:-NIFkb6s0L_z97mzdrcc:b-nj8sff) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L32)):*
> ```Python
>         self.pin = pin
>         self.gravity = gravity
>         self._pos_des = np.array([0., 0., 0.])
> ```

btw when are you use using underscore prefix for class members?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFkHlqE_NCrxuE0cHX:-NIFkHlqE_NCrxuE0cHY:bb7dwio) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L39)):*
> ```Python
>         """
>         Args:
>           goal The desired position of the pin (no orientation)
> ```

btw 
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 54 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFkpyj7B1effZ3rzMl:-NIFkpyj7B1effZ3rzMm:b-pfhyko) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L54)):*
> ```Python
>         force = -mass * self.gravity + mass * self.Kp * (
>             self._pos_des - pose_curr.p) + mass * self.Kd * -velocity
>         #force = np.array([0., 0., 0.])
> ```

btw remove commented out code if don't need it any longer
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 59 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFlKe82tzinX3VuKlA:-NIFlKe82tzinX3VuKlB:b9crunn) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L59)):*
> ```Python
> 
> 
> class RollingPinInverseDynamicsController:
> ```

btw it might make sense to define an abstract base class for the Controller in order to define the interface since there will be multiple classes implementing that interface
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 76 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFleTH9FWh8VdJaPqD:-NIFleTH9FWh8VdJaPqE:bhj1q5z) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L76)):*
> ```Python
>     @property
>     def cameras(self):
>         return dict(hand_camera=MountedCameraConfig(
> ```

btw one comment on what these constants are / what they're from would be helpful
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 76 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFoFD9-mqSyNKkzVIo:-NIFoFD9-mqSyNKkzVIp:bsas8mk) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L76)):*
> ```Python
>     @property
>     def cameras(self):
>         return dict(hand_camera=MountedCameraConfig(
> ```

btw why does the Rolling pin have a camera associated with it?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 92 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFmYjK9R8Hbwcqh_81:-NIFmYjK9R8Hbwcqh_82:b-bvyhzq) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L92)):*
> ```Python
> 
> 
> class RollingPin:
> ```

btw does it make sense to test this class?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 119 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFm0uM9LerozI6c1Wb:-NIFm0uM9LerozI6c1Wc:b5vrf57) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L119)):*
> ```Python
>         # Build the rolling pin actor
>         actor_builder: sapien.ActorBuilder = self.scene.create_actor_builder()
>         capsule_radius = 0.03
> ```

btw you might make this and other constants class member constants 
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 157 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFmne82COBKyNTVoxs:-NIFmne82COBKyNTVoxt:bl4ndcg) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L157)):*
> ```Python
> 
>     @property
>     def action_space(self):
> ```

btw this seems like it could be a class member initialized in __init__ rather than a `property`
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 160 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFmz4j57whRejvmY_S:-NIFmz4j57whRejvmY_T:bpje2cw) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L160)):*
> ```Python
>         return spaces.Box(low=np.array([-1.] * 6), high=np.array([1.] * 6))
> 
>     def reset(self, init_qpos=None):
> ```

btw do we want to use types? if so is this typing.List or np.ndarray or either?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 11 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFnTj726BI-LXLlfDF:-NIFnTj726BI-LXLlfDG:btd3wjm) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L11)):*
> ```Python
> from mani_skill2.agents.configs.panda.variants import PandaPinchConfig
> from mani_skill2.agents.configs.rolling_pin.defaults import RollingPinDefaultConfig
> ```

btw why this line break?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 18 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFnWlIAIYX4an9A4Jw:-NIFnWlIAIYX4an9A4Jx:b-j9r9n2) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L18)):*
> ```Python
> from mani_skill2.utils.sapien_utils import get_entity_by_name, vectorize_pose
> 
> import warp as wp
> ```

btw should this be imported above with h5py etc?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 36 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFp67f0fjwDgvqNg-S:-NIFp67f0fjwDgvqNg-T:bqgau1t) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L36)):*
> ```Python
> 
> @register_gym_env("Rolling-v0", max_episode_steps=10000)
> class RollingEnv(MPMBaseEnv):
> ```

btw does it make sense to have some tests?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 71 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFnvbz9k9EJoIfKTTW:-NIFnvbz9k9EJoIfKTTX:b5t6dtb) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L71)):*
> ```Python
> 
>         # I might need to tune the Young's modulus later.
>         E = 2E5
> ```

btw any comments giving context or a reference for how these constants are set would be helpful
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 184 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFpQhp0WKSEE3uJzJJ:-NIFpQhp0WKSEE3uJzJK:b-xj14r6) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L184)):*
> ```Python
> 
>             # Compute the wrench from applied by the controller.
>             if self.mpm_states[-1].struct.error.numpy()[0] == 1:
> ```

btw what's this condition checking?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 194 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFpf-DC0-XO7Fwcqrl:-NIFpf-DC0-XO7Fwcqrm:b-7hfy59) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L194)):*
> ```Python
>             for actor, tf in zip(self._coupled_actors, tfs):
>                 if actor.type not in ["kinematic", "static"]:
>                     if actor is self.agent.robot:
> ```

btw it might be slightly clearer if you do 
```python
# Apply wrench force if this actor is the agent (rolling pin).
if actor is self.agent.robot:
  tf[3:] += controller_wrench[:3]
  tf[:3] += controller_wrench[3:6]
actor.add_force_torque(tf[3:], tf[:3])
```

**Review by hongkai-dai — COMMENTED** [review]
Checkpoint. I will address the rest of the comments tomorrow.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NILoW9rA68uh8HEXur5:b8dtjjw)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`examples/demo_rolling.py` line 46 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEZH9xAaGu0nE8uqdf:-NILiVr87gnB7ZsjmNLk:b-7zdhd0) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L46)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw what's this doing?
</blockquote></details>

Done.

This comment was copied from another file. It is obsolete.
___
*[`examples/demo_rolling.py` line 47 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFjKhvBLGCG-5I66ur:-NILjdFoENnTTcXCqbt0:bnrbnyr) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L47)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw alternative way to do this would be to use a map like:
```python
KEY_TO_ACTION_MAP = {
  "i": [EE_ACTION, 0, 0],
...
}

# Then in this for loop:
if key == "q":
  break
action += KEY_TO_ACTION_MAP[key]
```

Is that better? Maybe slightly
</blockquote></details>

I think this KEY_TO_ACTION_MAP works great for the revision r1, where we only changes the position. In the current version (r2), the keystroke commands both the position and the orientation, and changes different variables (`position` and `quaternion`). It becomes harder to write the KEY_TO_ACTION_MAP as the type of action (position or quaternion) is different for each stroke. Hence I would like to keep the current code. What do you think?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 20 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEauiR2ppmeIyr_uTK:-NILkY0sDivznP1W6YqI:b-chtky2) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L20)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

maybe missing something, but what's the purpose of these?
</blockquote></details>

I think this annotates the member variable in this class, together with the type of each variable. I am trying to follow the convention in ManiSkill2 repo, for example in https://github.com/haosulab/ManiSkill2/blob/9885db8cf1df374277ca74a9d6234087ceb269f2/mani_skill2/agents/base_agent.py#L35-L50

Also see this in PEP https://peps.python.org/pep-0526/#class-and-instance-variable-annotations
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 32 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFkb6s0L_z97mzdrcb:-NILllxY2iEg2KfCeQ0w:b2300j0) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L32)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw when are you use using underscore prefix for class members?
</blockquote></details>

When the variable is "private" (that I don't want the external user to see it), I use underscore prefix.
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFkHlqE_NCrxuE0cHX:-NILm7w4EQZkzEwHgKc6:bbnh7qb) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L39)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw 
</blockquote></details>

Sorry is this an incomplete comment?
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 59 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFlKe82tzinX3VuKlA:-NILmH0tAnbmnmtG4zL3:b-i9i7zo) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L59)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw it might make sense to define an abstract base class for the Controller in order to define the interface since there will be multiple classes implementing that interface
</blockquote></details>

Good call. I will do that when I start to implement RollingPinInverseDynamicsController.

I added a TODO here.
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 76 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFleTH9FWh8VdJaPqD:-NILn82-6wo-gWAVS4JV:b-z62t2t) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L76)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw one comment on what these constants are / what they're from would be helpful
</blockquote></details>

Done. I added the comment to the class to explain where they are from.
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 76 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFoFD9-mqSyNKkzVIo:-NILnQae7I4NwVmcHl4r:bpitu52) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L76)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw why does the Rolling pin have a camera associated with it?
</blockquote></details>

Done. You are right. This camera is redundant.

**Review by blake-wulfe-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @hongkai-dai)

___
*[`examples/demo_rolling.py` line 47 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFjKhvBLGCG-5I66ur:-NIUV9pf5b88V1AAK-dB:bjfdnqt) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/examples/demo_rolling.py#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this KEY_TO_ACTION_MAP works great for the revision r1, where we only changes the position. In the current version (r2), the keystroke commands both the position and the orientation, and changes different variables (`position` and `quaternion`). It becomes harder to write the KEY_TO_ACTION_MAP as the type of action (position or quaternion) is different for each stroke. Hence I would like to keep the current code. What do you think?
</blockquote></details>

sure, makes sense. It might help the readability to extract the logic into a function
___
*[`mani_skill2/agents/robots/rolling_pin.py` line 20 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIEauiR2ppmeIyr_uTK:-NIUVJ990nmKUwmqTvhQ:b-w763bs) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/agents/robots/rolling_pin.py#L20)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this annotates the member variable in this class, together with the type of each variable. I am trying to follow the convention in ManiSkill2 repo, for example in https://github.com/haosulab/ManiSkill2/blob/9885db8cf1df374277ca74a9d6234087ceb269f2/mani_skill2/agents/base_agent.py#L35-L50

Also see this in PEP https://peps.python.org/pep-0526/#class-and-instance-variable-annotations
</blockquote></details>

I did not know about this, thanks!

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 194 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFpf-DC0-XO7Fwcqrl:-NIaAFf2Byhmxo_MJqRq:b-ngmy6z) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L194)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Since `tf` is a reference to some internal data of `self.mpm_states`, I am concerned that modifying `tf` would change `self.mpm_states`, which I don't fully understand and hence hesitant to modify.
</blockquote></details>

got it, good point

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 194 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFpf-DC0-XO7Fwcqrl:-NIaCF1G4YJKUTilCTsm:b3blcfy) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L194)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

got it, good point
</blockquote></details>

actually if that's currently the case I think we should copy it out each time to avoid bugs related to this. I think it's this line you're referring to? `tfs = [s.ext_body_f.numpy() for s in self.mpm_states[:-1]]` if so could just do `tfs = [s.ext_body_f.numpy().copy() for s in self.mpm_states[:-1]]`
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 118 at r4](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIaBL8z1BtBHNiiflfu:-NIaBL8z1BtBHNiiflfv:b-ppo5tc) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/19f27f4e01ec617410fb492fe4d4875a3338d0f2/mani_skill2/envs/mpm/rolling_env.py#L118)):*
> ```Python
> 
>     def _load_agent(self):
>         self.agent = RollingPin(
> ```

btw I typically think of "agent" as referring to the external object that interacts with the environment. Is this following some convention or something?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 36 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIFp67f0fjwDgvqNg-S:-NIaDxoQCXJvVmnR9cEB:b7vl1ag) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/f0d9a0db26f93f4f7e9d512918262dba5d9fe194/mani_skill2/envs/mpm/rolling_env.py#L36)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added the test `test_rolling_env.py`
</blockquote></details>

Is that included in this pr? don't see it but might be missing it

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 201 at r4](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-NIcZCU053aaB3sJfL9K:-NIcdXX73IQt_s9-2LuZ:bq0ncok) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/19f27f4e01ec617410fb492fe4d4875a3338d0f2/mani_skill2/envs/mpm/rolling_env.py#L201)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I plan to do it in the next PR, that I will add
```py
def step(self, action)
```
where we define the `action` as the end pose of the rolling pin sweeping action. Inside this function it will then interpolate the current pose and the desired final pose, and then call this `step_action_one_way_coupling` in a loop to go through each of the interpolated pose.
</blockquote></details>

sounds good

**Review by blake-wulfe-tri — COMMENTED** [review]
I'm planning to try it out on my puget tomorrow, but I wouldn't let that hold up the PR :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/1#-:-NIcdarI2AkTH-jrixHm:b4u39mm)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Pull request merged**
