### PR TITLE
GradientShooting works on a batch of action sequences.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-:-NQ6ko7w7E6uVFpJS7kK:b9e17as)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 
Sorry for the delay

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-:-NQQtG5HCJWiClMvFb-w:bq495dr)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 64 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQmPuwCV2hlYpf65TS:-NQQmPuwCV2hlYpf65TT:b-f8tcmm) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L64)):*
> ```Python
>         sequence in each roll out.
> 
>         Args:
> ```

btw looks like missing some args
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQQqYep1gvpmKZGrwhd:b9m8ea1) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
> ```Python
>         # act_sequences is a non-leaf Tensor and the optimizer cannot optimize a
>         # non-leaf tensor. Hence this function will modify self.act_sequences.
>         # act_sequences = self.act_sequences.clone()
> ```

btw mean for this to be commented? `# act_sequences = self.act_sequences.clone()`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQR1BVkDkitfrjd-bKO:by16kwx) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw mean for this to be commented? `# act_sequences = self.act_sequences.clone()`
</blockquote></details>

I modified the documentation. Is it more clear now?

I cannot use 
```py
act_sequences = self.act_sequences.clone()
optimizer = self.optimizer(act_sequences)
```
since act_sequences is not a leaf tensor (obtained by cloning from self.act_sequences) and hence the optimizer cannot optimize a non-leaf tensor. Do you know how to get around this?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQR5Zly6uehXFcmGiCq:b-jyjwa7) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I modified the documentation. Is it more clear now?

I cannot use 
```py
act_sequences = self.act_sequences.clone()
optimizer = self.optimizer(act_sequences)
```
since act_sequences is not a leaf tensor (obtained by cloning from self.act_sequences) and hence the optimizer cannot optimize a non-leaf tensor. Do you know how to get around this?
</blockquote></details>

you might try `act_sequences = self.act_sequences.clone().requires_grad_()`?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQR7sIXDSGUCrYgvUVe:b-8nk2zz) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
Thanks! But I still get the same error
```
            if not self.defaults.get('differentiable', None) and not (param.is_leaf or param.retains_grad):
>               raise ValueError("can't optimize a non-leaf Tensor")
E               ValueError: can't optimize a non-leaf Tensor
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQRaEo5-sBRnjWwgToW:b-xeqsms) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks! But I still get the same error
```
            if not self.defaults.get('differentiable', None) and not (param.is_leaf or param.retains_grad):
>               raise ValueError("can't optimize a non-leaf Tensor")
E               ValueError: can't optimize a non-leaf Tensor
```
</blockquote></details>

Using deepcopy solves the problem.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 108 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24#-NQQqYep1gvpmKZGrwhc:-NQRcglO-Svz0QzNVCN_:bb70w76) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/eb98015dd2ebb211c0902f64681266fec9543680/mani_skill2/algorithms/gradient_shooting.py#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Using deepcopy solves the problem.
</blockquote></details>

Nice

**Pull request merged**
