### PR TITLE
RollingEnv can observe either particle position or heightmap.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-:-NRk1084-vo0pG_EeS1Y:b9e17as)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-:-NS4dV4XEqvuV_8Or8yl:bg7igkv)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 152 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-NS4dC0q289GsQn6ln0E:-NS4dC0q289GsQn6ln0F:be5l3wf) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/331662eb1f7f0d96575f496255d91d68c50a6254/mani_skill2/envs/mpm/rolling_env.py#L152)):*
> ```Python
>         super().__init__(*args, **kwargs)
>         # Overwrite the inferred observation space with valid bounds.
>         if self.obs_mode == "heightmap":
> ```

btw does this need an option for the pointcloud? Is the pointcloud a fixed number of points? If not, I'm not actually sure what the proper way to define the obs space would be

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 152 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-NS4dC0q289GsQn6ln0E:-NS4j_swB-M--7-RYlOZ:b-jemlt5) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/331662eb1f7f0d96575f496255d91d68c50a6254/mani_skill2/envs/mpm/rolling_env.py#L152)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw does this need an option for the pointcloud? Is the pointcloud a fixed number of points? If not, I'm not actually sure what the proper way to define the obs space would be
</blockquote></details>

The pointcloud option is already defined in the base class `MPMBaseEnv` at https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/mpm/base_env.py#L55-L58.

and `BaseEnv` in https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/sapien_env.py#L53-L56
I haven't looked carefully the dimensionality of the point cloud. ManiSkill2 have a method to get the point cloud https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/sapien_env.py#L265-L295. My understanding is that it gets the point cloud of everything, including the dough, the table and the robot. While in Katherine's case I think she only wants the point cloud of the dough (including the bottom part of the dough that is touching the table, and hence cannot be seen from the camera)

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 152 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-NS4dC0q289GsQn6ln0E:-NS4nbrpDmv_klFRd4QJ:bl5gqq4) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/331662eb1f7f0d96575f496255d91d68c50a6254/mani_skill2/envs/mpm/rolling_env.py#L152)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The pointcloud option is already defined in the base class `MPMBaseEnv` at https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/mpm/base_env.py#L55-L58.

and `BaseEnv` in https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/sapien_env.py#L53-L56
I haven't looked carefully the dimensionality of the point cloud. ManiSkill2 have a method to get the point cloud https://github.com/hongkai-dai/ManiSkill2/blob/32ef6b3dc62f82f3d555fc5919778a1750977820/mani_skill2/envs/sapien_env.py#L265-L295. My understanding is that it gets the point cloud of everything, including the dough, the table and the robot. While in Katherine's case I think she only wants the point cloud of the dough (including the bottom part of the dough that is touching the table, and hence cannot be seen from the camera)
</blockquote></details>

Oh ok. I don't know how to use the internals of maniskill to get the pointcloud for just the dough, but I assume there's some way. I wonder if it makes sense to just start w/ the pointcloud of everything?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 152 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/29#-NS4dC0q289GsQn6ln0E:-NS7MX9t8W5rWtcgOj52:b-rubers) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/331662eb1f7f0d96575f496255d91d68c50a6254/mani_skill2/envs/mpm/rolling_env.py#L152)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

Oh ok. I don't know how to use the internals of maniskill to get the pointcloud for just the dough, but I assume there's some way. I wonder if it makes sense to just start w/ the pointcloud of everything?
</blockquote></details>

I think that sounds good to get the whole point cloud, if we set the obs_mode to pointcloud. I think for this PR we want to address Katherine's feature request to provide all the particles, hence I append this extra `obs_mode=particle_positions`.

**Pull request merged**
