### PR TITLE
add RandomShootingAgent.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-:-NOwp1dZ6w1AAxwwlCjX:b9e17as)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-:-NOxAprH4FCoZdqf3EaD:bg7igkv)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/agents/planners/random_shooting.py` line 9 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx63DS2St8149vyL3z:-NOx63DS2St8149vyL4-:b6ezf7) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L9)):*
> ```Python
> 
> 
> class RandomShootingAgent:
> ```

btw should this inherit from `GymAgent`? I think `GymAgent` is still somewhere under examples/... so maybe we should move that somewhere into the library
___
*[`mani_skill2/agents/planners/random_shooting.py` line 57 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx81sM81A2ZV3DOFoT:-NOx81sM81A2ZV3DOFoU:bp05fdr) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L57)):*
> ```Python
>             # Repeat initial_state along dim 0 for num_rollouts times.
>             # Is this the best way to repeat the state?
>             states = initial_state.unsqueeze(0).repeat(
> ```

btw
I don't think you need to unsqueeze and you can do initial_state.ndim instead of len, but please double check
```python
num_repeats = [num_rollouts] + [1] * (initial_state.ndim - 1)
states = initial_state.repeat(num_repeats)
```



_Code quote:_
```Python
            states = initial_state.unsqueeze(0).repeat(
                [num_rollouts] + [1] * len(initial_state.shape)
            )
```
___
*[`mani_skill2/agents/planners/random_shooting.py` line 60 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx9HwJ9L7TVbINzdwH:-NOx9HwJ9L7TVbINzdwI:bfc2fhw) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L60)):*
> ```Python
>                 [num_rollouts] + [1] * len(initial_state.shape)
>             )
>             state_rollouts.append(states)
> ```

btw not that this is matters, but since you know num_rollouts and the size of the state, you could preallocate this tensor and index into it instead of appending. My guess is that when using heightmaps and a large number for `num_rollouts`, and if you preallocate the states in __init__ it might be faster enough to notice the difference. But, it's not worth worrying about for now
___
*[`mani_skill2/agents/planners/random_shooting.py` line 67 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx9usfEbpRoyjXZ8J8:-NOx9usfEbpRoyjXZ8J9:b-6knq5j) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L67)):*
> ```Python
>                     states, action_sequences[:, i, :]
>                 )
>                 total_rewards += gamma_power * rewards
> ```

btw could just do this?
```python
total_rewards += self.discount_factor ** i * rewards
```
that way you avoid `gamma_power` entirely



_Code quote:_
```Python
                total_rewards += gamma_power * rewards
                gamma_power *= self.discount_factor
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/agents/planners/random_shooting.py` line 9 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx63DS2St8149vyL3z:-NOzMMsH-R87cRYZ8mFL:b-yh16l6) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L9)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw should this inherit from `GymAgent`? I think `GymAgent` is still somewhere under examples/... so maybe we should move that somewhere into the library
</blockquote></details>

Done. Good call.
___
*[`mani_skill2/agents/planners/random_shooting.py` line 57 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx81sM81A2ZV3DOFoT:-NOzN03j1JKlezOv4AUd:b-332mu5) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L57)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw
I don't think you need to unsqueeze and you can do initial_state.ndim instead of len, but please double check
```python
num_repeats = [num_rollouts] + [1] * (initial_state.ndim - 1)
states = initial_state.repeat(num_repeats)
```
</blockquote></details>

Neat, thanks a lot!
___
*[`mani_skill2/agents/planners/random_shooting.py` line 60 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx9HwJ9L7TVbINzdwH:-NOz_pdJ87orjqGKDJK8:b-yh16lj) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L60)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw not that this is matters, but since you know num_rollouts and the size of the state, you could preallocate this tensor and index into it instead of appending. My guess is that when using heightmaps and a large number for `num_rollouts`, and if you preallocate the states in __init__ it might be faster enough to notice the difference. But, it's not worth worrying about for now
</blockquote></details>

Done. Good call!
___
*[`mani_skill2/agents/planners/random_shooting.py` line 67 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx9usfEbpRoyjXZ8J8:-NOz_sns-wotGnuUVlU_:bouwzeq) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L67)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw could just do this?
```python
total_rewards += self.discount_factor ** i * rewards
```
that way you avoid `gamma_power` entirely
</blockquote></details>

Done.

I was trying to avoid using power function, but that is a premature optimization.

**Review by blake-wulfe-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/agents/gym_agent.py` line 1 at r3](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOzevsV43ZK9Edv1aPR:-NOzevsV43ZK9Edv1aPS:bfizo8c) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/787b41aa0da7af9c52712a7f93f38dd072bb2b4e/mani_skill2/agents/gym_agent.py#L1)):*
> ```Python
> import abc
> ```

I think `mani_skill2/agents` is for "agents" in the mani_skill2 sense (i.e., I think things that move in the simulation). Can we instead put this class in a different directory? Like "algorithms"? that's sort of vague, but that's what rllib uses (https://github.com/ray-project/ray/tree/master/rllib/algorithms)
___
*[`mani_skill2/agents/planners/random_shooting.py` line 67 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOx9usfEbpRoyjXZ8J8:-NOzfcrx6ochVdrqQihl:b8fuyy8) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/97230c803e05942e1e219aa57b96aff9e56760c0/mani_skill2/agents/planners/random_shooting.py#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.

I was trying to avoid using power function, but that is a premature optimization.
</blockquote></details>

haha oh didn't even occur to me. I guess either is fine

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/agents/gym_agent.py` line 1 at r3](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOzevsV43ZK9Edv1aPR:-NOzu2Yq1hQSXmb434an:bl3jc70) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/787b41aa0da7af9c52712a7f93f38dd072bb2b4e/mani_skill2/agents/gym_agent.py#L1)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I think `mani_skill2/agents` is for "agents" in the mani_skill2 sense (i.e., I think things that move in the simulation). Can we instead put this class in a different directory? Like "algorithms"? that's sort of vague, but that's what rllib uses (https://github.com/ray-project/ray/tree/master/rllib/algorithms)
</blockquote></details>

Done. I also moved the planners/random_shooting to this algorithms folder as it inherits from GymAgent

**Review by blake-wulfe-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/agents/gym_agent.py` line 1 at r3](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/18#-NOzevsV43ZK9Edv1aPR:-NP-3ZC47IJMlYRxUQye:b-83sjoh) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/787b41aa0da7af9c52712a7f93f38dd072bb2b4e/mani_skill2/agents/gym_agent.py#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I also moved the planners/random_shooting to this algorithms folder as it inherits from GymAgent
</blockquote></details>

Nice!

**Pull request merged**
