### PR TITLE
Add TransitionTupleDataset

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-:-NM7g7Hc3otN296SelV-:b9e17as)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-:-NMCc-3L9e2HTYPM19-9:bg7igkv)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`examples/dough_model_learning/data_generation.py` line 123 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-NMCbWW-1d_hF0-1DRr6:-NMCbWW-1d_hF0-1DRr7:boj7uhw) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/8f88d4054f471de6ea4a5f0fef29ffc52408ac09/examples/dough_model_learning/data_generation.py#L123)):*
> ```Python
> 
> @dataclass
> class TransitionTupleDatasetOptions:
> ```

btw I think we discussed this previously, but why would we prefer this to just passing to options directly to the class?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`examples/dough_model_learning/data_generation.py` line 123 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-NMCbWW-1d_hF0-1DRr6:-NMCdAqCDHNHeskIno_O:b-k2cz36) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/8f88d4054f471de6ea4a5f0fef29ffc52408ac09/examples/dough_model_learning/data_generation.py#L123)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw I think we discussed this previously, but why would we prefer this to just passing to options directly to the class?
</blockquote></details>

I am not familiar with what is the convention in python/learning community. Is it preferable to pass many input with default values? I mostly write C++ code, where I wrap many arguments with default values into a struct, and just pass in that struct.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`examples/dough_model_learning/data_generation.py` line 123 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-NMCbWW-1d_hF0-1DRr6:-NMFFmvTE8-Vq5_Bxrb9:bowni1g) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/8f88d4054f471de6ea4a5f0fef29ffc52408ac09/examples/dough_model_learning/data_generation.py#L123)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not familiar with what is the convention in python/learning community. Is it preferable to pass many input with default values? I mostly write C++ code, where I wrap many arguments with default values into a struct, and just pass in that struct.
</blockquote></details>

I think people do that in c++ for a variety of reasons, with the main ones I'm aware of being (i) lack of named arguments in c++ (so with many arguments it can be hard to say which is which based on the call) (this was maybe added at some point?) (ii) ability to parse the arguments from config files in a principled manner. There might be others, but I think those are the main ones?

In python there are named arguments, so really only the second reason makes sense. For example, in Anzu they use the pattern of a *Config object containing parameters in order to make parsing the config from yaml files easier / more principled. 

So I would say it really only makes sense to separate out the arguments into a separate struct if you're planning to parse them from a config file, which is probably not the case here. Of course, you can imagine this codebase getting more complicated in the future and our using config files, but we can also refactor to do that later.

The conclusion being: in python this isn't really the convention (to my knowledge) and in this case I don't think it makes too much sense, but ultimately it doesn't really matter too much.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`examples/dough_model_learning/data_generation.py` line 123 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6#-NMCbWW-1d_hF0-1DRr6:-NMFw3p3BSQ7CUeUUJHD:b3h5rd7) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/8f88d4054f471de6ea4a5f0fef29ffc52408ac09/examples/dough_model_learning/data_generation.py#L123)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I think people do that in c++ for a variety of reasons, with the main ones I'm aware of being (i) lack of named arguments in c++ (so with many arguments it can be hard to say which is which based on the call) (this was maybe added at some point?) (ii) ability to parse the arguments from config files in a principled manner. There might be others, but I think those are the main ones?

In python there are named arguments, so really only the second reason makes sense. For example, in Anzu they use the pattern of a *Config object containing parameters in order to make parsing the config from yaml files easier / more principled. 

So I would say it really only makes sense to separate out the arguments into a separate struct if you're planning to parse them from a config file, which is probably not the case here. Of course, you can imagine this codebase getting more complicated in the future and our using config files, but we can also refactor to do that later.

The conclusion being: in python this isn't really the convention (to my knowledge) and in this case I don't think it makes too much sense, but ultimately it doesn't really matter too much.
</blockquote></details>

Thanks Blake for the detailed explanation. That makes a lot of sense, I switched to using named argument with default values.

**Pull request merged**
