### PR TITLE
Compute heightmap of the dough.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-:-NIeB6AS3PaxZVMBbUer:b9e17as)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-:-NIey7w71q34DJv4ngjt:bg7igkv)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 80 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIex-S12bhpboTApCZl:-NIex-S2Cc_sIS6iTFNV:b7r107w) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/13cf59b38c6e99bd994f10310bfd3335126eddab/mani_skill2/envs/mpm/rolling_env.py#L80)):*
> ```Python
>         friction_angle = 0.5
>         cohesion = 0.05
>         if hasattr(self, "_initial_height_map"):
> ```

btw would it make sense to just initialize self._initial_height_map to `np.ones((10,10)) * 0.01` in `__init__` to simplify this logic (can always assume the initial height map exists)?
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 292 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIexubhBVR_yBShQ33K:-NIexubhBVR_yBShQ33L:b-g5rcf6) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/13cf59b38c6e99bd994f10310bfd3335126eddab/mani_skill2/envs/mpm/rolling_env.py#L292)):*
> ```Python
>                 h_index = grid_size_h
>             if w_index < 0:
>                 w_index = 0
> ```

btw does it make sense to assert that these conditions don't hold or could there be a valid case where they're met?



_Code quote:_
```Python
            if h_index < 0:
                h_index = 0
            if h_index > grid_size_h - 1:
                h_index = grid_size_h
            if w_index < 0:
                w_index = 0
            if w_index > grid_size_w - 1:
                w_index = grid_size_w - 1
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 80 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIex-S12bhpboTApCZl:-NIfG1PH5I9LWO-dmGbf:b-qgcjqt) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/13cf59b38c6e99bd994f10310bfd3335126eddab/mani_skill2/envs/mpm/rolling_env.py#L80)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw would it make sense to just initialize self._initial_height_map to `np.ones((10,10)) * 0.01` in `__init__` to simplify this logic (can always assume the initial height map exists)?
</blockquote></details>

Good call.

This function `_initialize_mpm` is called by the parent class `__init__()`, so it requires `_initial_height_map` being set before calling the parent class `__init__()`. As a C++ programmer, I didn't realize in python `__init__()` function I can set the member attributes value BEFORE calling the parent class `__init__()`.  (This is different from C++ constructor where the first thing is to call the parent class constructor). TIL python initializer is different from C++ constructor.
___
*[`mani_skill2/envs/mpm/rolling_env.py` line 292 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIexubhBVR_yBShQ33K:-NIfGgPsD8wKZjBloarh:b-l0n865) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/13cf59b38c6e99bd994f10310bfd3335126eddab/mani_skill2/envs/mpm/rolling_env.py#L292)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw does it make sense to assert that these conditions don't hold or could there be a valid case where they're met?
</blockquote></details>

Yes, these condition could be met. In `MPMEnvBuilder`, when it initialize the particle given the height map, there is an optional argument to randomly perturb the particle position by a small delta, which could cause the resulting particle position going outside of the specified range, and causing`h_index` and `w_index` to go out side of range [0, grid_size - 1].

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 80 at r1](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIex-S12bhpboTApCZl:-NIfQmvnCKbbZIzC5yi7:bmi8ppe) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/13cf59b38c6e99bd994f10310bfd3335126eddab/mani_skill2/envs/mpm/rolling_env.py#L80)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call.

This function `_initialize_mpm` is called by the parent class `__init__()`, so it requires `_initial_height_map` being set before calling the parent class `__init__()`. As a C++ programmer, I didn't realize in python `__init__()` function I can set the member attributes value BEFORE calling the parent class `__init__()`.  (This is different from C++ constructor where the first thing is to call the parent class constructor). TIL python initializer is different from C++ constructor.
</blockquote></details>

:100:

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/maniskill2/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/test/test_rolling_env.py` line 9 at r2](https://reviewable.io/reviews/hongkai-dai/maniskill2/2#-NIfR9nxBRygxDHHKBwp:-NIfR9nxBRygxDHHKBwq:bxxir7z) ([raw file](https://github.com/hongkai-dai/maniskill2/blob/0f30fe60567d0bd558c7dbca0c1b7639a8601882/mani_skill2/envs/mpm/test/test_rolling_env.py#L9)):*
> ```Python
> 
> 
> class TestRollingEnv(unittest.TestCase):
> ```

btw one test for an environment that seems too simple, but that often catches things is just making sure it can run a rollout like
```python
env.reset()
for _ in range(num_steps):
  env.step(env.action_space.sample())
```
where if that process results in an exception the testing code should result in an exception

**Pull request merged**
