### PR TITLE
Add GradientShootingAgent

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@blake-wulfe-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-:-NP1SuNK5NNufqL9iMrL:b9e17as)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

**Review by blake-wulfe-tri — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-:-NP3bNp46zQNRaBZsjj3:b-uwkowd)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 4 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3XR_QEbay5TrMFc-8:-NP3XR_QEbay5TrMFc-9:b-127hnc) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L4)):*
> ```Python
> import torch
> 
> from typing import Tuple
> ```

btw typing is built in to python so conventionally would go before numpy / torch
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Z6NkDVVcBhuvMV56:-NP3Z6NkDVVcBhuvMV57:b-x74ola) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L10)):*
> ```Python
> 
> 
> class GradientShootingAgent(GymAgent):
> ```

btw a brief comment on the approach of this algorithm would be helpful
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3b3L5Dr32S2TEhYNi:-NP3b3L5Dr32S2TEhYNj:b9gipxu) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L10)):*
> ```Python
> 
> 
> class GradientShootingAgent(GymAgent):
> ```

btw I was trying to debug the RandomShootingAgent last night and was wondering: what is the typical strategy for debugging these algorithms? What additional information do they typically output? What visualizations are best? Should we have a RandomShootingAgentVisualizer class (and same for every other planning algorithm) that visualizes the internals for debugging?
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NP3Zw7k20pxl-0x9hye:bbjoa7) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
> ```Python
>         self.gradient_steps = gradient_steps
> 
>     def set_action_sequence_init(self, act_sequence: torch.Tensor):
> ```

btw what will call this in practice? I guess this is the warm start
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3ZiNTEqstBDmYWW3L:-NP3ZiNTEqstBDmYWW3M:b-8vq9hp) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
> ```Python
>         self.act_sequence = act_sequence
> 
>     def step(self, obs: torch.Tensor) -> torch.Tensor:
> ```

btw I need to add an additional return for GymAgent to return some info in a dict so it's easier to debug / visualize the internal steps 
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3a3_j378RlXF1Bck_:-NP3a3_j378RlXF1Bcka:b-vh05y3) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
> ```Python
>         self.act_sequence = act_sequence
> 
>     def step(self, obs: torch.Tensor) -> torch.Tensor:
> ```

btw maybe add a TODO to perform all this in batch? since we're running a forward pass on the GPU I wouldn't expect doing it over a batch of actions would be much slower
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NP3_ZPoDf4scC9GL92_:b-ok7qwb) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
> ```Python
>             optimizer.zero_grad()
>             _, total_reward = self.generative_env.rollout(
>                 state.unsqueeze(0), self.act_sequence.unsqueeze(0), self.discount_factor
> ```

btw should this be using `best_act_sequence` instead of `self.act_sequence`? I guess not b/c self.act_sequence is updated in place by the optimizer? If that's the case should we really be updating the class member / should we instead make a local copy and update that? 
___
*[`mani_skill2/dynamics/generative_env.py` line 90 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3aVs_8Y-JH8qST35E:-NP3aVs_8Y-JH8qST35F:b-6671s2) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/dynamics/generative_env.py#L90)):*
> ```Python
>             discount_factor (float): discount the transition step by this factor per step.
> 
>         Returns:
> ```

btw commenting on the shape of these like you did for the arguments in would be helpful
___
*[`mani_skill2/tests/algorithms/test_gradient_shooting.py` line 14 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3aqQp2rfMeFWe9Ft5:-NP3aqQp2rfMeFWe9Ft6:bhnfq2c) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/tests/algorithms/test_gradient_shooting.py#L14)):*
> ```Python
>     @pytest.mark.parametrize("gradient_steps", (2, 5))
>     def test_step(self, state_size, act_size, planning_steps, gradient_steps):
>         device = "cuda"
> ```

btw you might parametrize based on the device as well (`cuda` vs `cpu`). I doubt we will be running on the cpu much, but that's a good way to catch bugs where the device is underspecified
___
*[`mani_skill2/tests/algorithms/test_gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_AzhEYkpoWqzjbo_:-NP3_AzhEYkpoWqzjboa:b-ymuky8) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/tests/algorithms/test_gradient_shooting.py#L35)):*
> ```Python
>                 state_init.unsqueeze(0), act_sequence_init.unsqueeze(0), discount_factor
>             )
>             print(reward_init)
> ```

btw probably want to remove prints

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 4 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3XR_QEbay5TrMFc-8:-NPAUEbn97HjTN_F5-ih:buvl8a8) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L4)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw typing is built in to python so conventionally would go before numpy / torch
</blockquote></details>

Done. We don't use Tuple in this file so I removed this line.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Z6NkDVVcBhuvMV56:-NPAUfQH0NTewIYpFzGK:b-yh16l6) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L10)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw a brief comment on the approach of this algorithm would be helpful
</blockquote></details>

Done. Good call.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3b3L5Dr32S2TEhYNi:-NPAUlcp9qJmsQ7vsbC2:b-f7c3yl) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L10)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw I was trying to debug the RandomShootingAgent last night and was wondering: what is the typical strategy for debugging these algorithms? What additional information do they typically output? What visualizations are best? Should we have a RandomShootingAgentVisualizer class (and same for every other planning algorithm) that visualizes the internals for debugging?
</blockquote></details>

I think the debugging is sort of ad-hoc. For the random shooting approach, one possible debugging strategy is to print out the loss for each roll-out. What we want is the optimization landscape from the action sequence to the cumulative reward. But this landscape is in a high-dimensional space, hence I think the visualization is challenging. (We can visualize the roll-out with the dough though).
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPAVNme3l5XQbnALZCL:bitmhkh) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw what will call this in practice? I guess this is the warm start
</blockquote></details>

I think before calling `step` we should call this function to set the initial guess.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3a3_j378RlXF1Bck_:-NPA_QTHC8xK5Bf8_zkD:b-aqhtua) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw maybe add a TODO to perform all this in batch? since we're running a forward pass on the GPU I wouldn't expect doing it over a batch of actions would be much slower
</blockquote></details>

Cool, I will do that in my next PR. TIL using `retain_graph`.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NPAbpk_Eqno-LtKtd3P:bvmox5i) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw should this be using `best_act_sequence` instead of `self.act_sequence`? I guess not b/c self.act_sequence is updated in place by the optimizer? If that's the case should we really be updating the class member / should we instead make a local copy and update that? 
</blockquote></details>

I don't think this should use `best_act_sequence`. I think we always want to use the action sequence in the previous optimization iteration. But best_act_sequence could be the act sequence in multiple steps before, if the cumulative reward decreases in the last few optimization iterations.

I made `act_sequence` a class member because the optimizer needs to know the initial value of the action sequence. But `step` function currently only accepts `obs`, so I put `act_sequence` inside the class to store the initial value. If `step` function accepts more arguments, then I can pass the initial action sequence as an input argument to `step`. I personally prefer adding `act_sequence_init` as an argument in `step` function. What do you think?
___
*[`mani_skill2/dynamics/generative_env.py` line 90 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3aVs_8Y-JH8qST35E:-NPAd-f9Eos86oPp9fRC:b-yh16l6) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/dynamics/generative_env.py#L90)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw commenting on the shape of these like you did for the arguments in would be helpful
</blockquote></details>

Done. Good call.
___
*[`mani_skill2/tests/algorithms/test_gradient_shooting.py` line 14 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3aqQp2rfMeFWe9Ft5:-NPApQVVBz9lio32dcxZ:b-yh16l6) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/tests/algorithms/test_gradient_shooting.py#L14)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw you might parametrize based on the device as well (`cuda` vs `cpu`). I doubt we will be running on the cpu much, but that's a good way to catch bugs where the device is underspecified
</blockquote></details>

Done. Good call.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 10 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3b3L5Dr32S2TEhYNi:-NPDuGKX8j1gdDRcg4SD:bl2n41e) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L10)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the debugging is sort of ad-hoc. For the random shooting approach, one possible debugging strategy is to print out the loss for each roll-out. What we want is the optimization landscape from the action sequence to the cumulative reward. But this landscape is in a high-dimensional space, hence I think the visualization is challenging. (We can visualize the roll-out with the dough though).
</blockquote></details>

Ok sounds good. I'll think about this a bit more
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPDuJxx12_clc5sj7Qw:bnsutfv) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think before calling `step` we should call this function to set the initial guess.
</blockquote></details>

Ok, since this is running in the same for loop at any other GymAgent subclass, I think we either need to do that internally (i.e., at the beginning and end of this function initialize / store a warm start guess) or refactor to have a GymAgent class own an instance of this class, but we can figure that out later
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NPDunNs6YxtPduOKo3P:b-b1k789) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think this should use `best_act_sequence`. I think we always want to use the action sequence in the previous optimization iteration. But best_act_sequence could be the act sequence in multiple steps before, if the cumulative reward decreases in the last few optimization iterations.

I made `act_sequence` a class member because the optimizer needs to know the initial value of the action sequence. But `step` function currently only accepts `obs`, so I put `act_sequence` inside the class to store the initial value. If `step` function accepts more arguments, then I can pass the initial action sequence as an input argument to `step`. I personally prefer adding `act_sequence_init` as an argument in `step` function. What do you think?
</blockquote></details>

See my above comment about either needing to handle it internally or wrapping this class (basically I don't want to assume the code doing the rollout knows anything about the GymAgent subclass)

**Review by hongkai-dai — COMMENTED** [review]
Sorry for the delay, I was working on some paper today.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-:-NPF_Tac9pKvk9Y_2fs_:b-bwvn72)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPFXIVf6yBr7bFEVk4b:b-iti0jv) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
> refactor to have a GymAgent class own an instance of this class

To be clear, I guess what you mean here is
```py
class GradientShootingAgent(GymAgent):
    gradient_shooter: GradientShoorter
    def step(self, obs):
        return self.gradient_shooter.step(obs)

class GradientShooter:
  act_sequence: torch.Tensor
  def step(self, obs):
      # Do gradient descent on self.act_sequence


if __name__ == "__main__":
    agent = GradientShootingAgent()
    agent.gradient_shooter.act_sequence = act_sequence_init
    agent.step(obs)
```
Namely now GradientShootingAgent (which is a sub-class of GymAgent) will own an instance of GradientShooter. GradientShooter keeps an initial guess of the action sequence, and GradientShooter::step() actually does the gradient descent to optimize the action sequence.

If that is the case, it seems that the user still need to remember initializing act_sequence through `agent.gradient_shooter.act_sequence = foo`. So how is that different from the current code that calls `agent.set_act_sequence_init(foo)`?
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3ZiNTEqstBDmYWW3L:-NPFZA1e0XplXSeckDFz:b-o2upn) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

btw I need to add an additional return for GymAgent to return some info in a dict so it's easier to debug / visualize the internal steps 
</blockquote></details>

I added an empty dict as a return argument.

I am not sure what debug/visualize info should be contained inside this dict. In the DynamicsModel.step() function we do return a dictionary there. But that is a dictionary per simulation step. Now in the roll out we have multiple steps. Should I concatenate these dictionary returned in each step?
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NPFZpVM6y928qWOKQ8B:bc8u6cq) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
> basically I don't want to assume the code doing the rollout knows anything about the GymAgent subclass

Which rollout do you talk about? This GradientShootingAgent::step() method does a rollout inside its `step()` function, using the current action sequence, but this rollout is already inside GradientShootingAgent class so it doesn't hurt that it knows about this subclass.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPG2rvB-7ufua3Bg3SA:b-tjs3fg) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> refactor to have a GymAgent class own an instance of this class

To be clear, I guess what you mean here is
```py
class GradientShootingAgent(GymAgent):
    gradient_shooter: GradientShoorter
    def step(self, obs):
        return self.gradient_shooter.step(obs)

class GradientShooter:
  act_sequence: torch.Tensor
  def step(self, obs):
      # Do gradient descent on self.act_sequence


if __name__ == "__main__":
    agent = GradientShootingAgent()
    agent.gradient_shooter.act_sequence = act_sequence_init
    agent.step(obs)
```
Namely now GradientShootingAgent (which is a sub-class of GymAgent) will own an instance of GradientShooter. GradientShooter keeps an initial guess of the action sequence, and GradientShooter::step() actually does the gradient descent to optimize the action sequence.

If that is the case, it seems that the user still need to remember initializing act_sequence through `agent.gradient_shooter.act_sequence = foo`. So how is that different from the current code that calls `agent.set_act_sequence_init(foo)`?



</blockquote></details>

That's basically what I had in mind yes. The difference is that `GradientShootingAgent` is responsible for calling `GradientShooter.initialize_act_sequence` (and whatever logic is necessary for coming up with that sequence), and well as for remembering that action sequence in case we can to use part of it at the next timestep. Does that make sense? If not my guess is that I'm missing something about how that initial action sequence is determined.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3ZiNTEqstBDmYWW3L:-NPG3SHi9grD8bbSoWju:b-69cf3g) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added an empty dict as a return argument.

I am not sure what debug/visualize info should be contained inside this dict. In the DynamicsModel.step() function we do return a dictionary there. But that is a dictionary per simulation step. Now in the roll out we have multiple steps. Should I concatenate these dictionary returned in each step?
</blockquote></details>

I would just append them to a list as the loop runs. Though I would still return a `dict` from this function. So returning something like `dict(dyn_infos=list_of_dyn_infos)`
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NPG3qVlE66aDeaCX2pE:bve2fig) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> basically I don't want to assume the code doing the rollout knows anything about the GymAgent subclass

Which rollout do you talk about? This GradientShootingAgent::step() method does a rollout inside its `step()` function, using the current action sequence, but this rollout is already inside GradientShootingAgent class so it doesn't hurt that it knows about this subclass.
</blockquote></details>

I'm talking about this function: https://github.com/hongkai-dai/ManiSkill2/blob/main/mani_skill2/utils/rollout.py#L18 which is used for data generation as well as evaluation

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPJQCH3EuhMXk3B5B_C:bnnhnad) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

That's basically what I had in mind yes. The difference is that `GradientShootingAgent` is responsible for calling `GradientShooter.initialize_act_sequence` (and whatever logic is necessary for coming up with that sequence), and well as for remembering that action sequence in case we can to use part of it at the next timestep. Does that make sense? If not my guess is that I'm missing something about how that initial action sequence is determined.
</blockquote></details>

Sounds good. I will do it in my next PR. I think the proposed API (as we discussed in the slack is this):

1. We have the abstract GymAgent class.
2. We have a PlannerAgent class derived from GymAgent class. This PlannerAgent class looks like this
```py
class PlannerAgent(GymAgent):
    # planner is a concrete class, such as RandomShootingPlanner or GradientShootingPlanner
    planner
    def __init__(self, planner):
        self.planner = planner
    def step(self, obs) -> Tuple[torch.Tensor, Dict]:
        return self.planner.step(obs)
```
3. For each of the concrete planner class, such as `RandomShootingPlanner` or `GradientShootingPlanner`, they implement the `step` function. Also each planner will implement the planner-specific function, such as setting up the sampling distribution, setting up the initial value of the action sequence, etc.

Does this sound good to you?
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 39 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3ZiNTEqstBDmYWW3L:-NPJVAki08aj1BMducMd:b-896fix) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L39)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I would just append them to a list as the loop runs. Though I would still return a `dict` from this function. So returning something like `dict(dyn_infos=list_of_dyn_infos)`
</blockquote></details>

Done.
___
*[`mani_skill2/algorithms/gradient_shooting.py` line 49 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3_ZPoDf4scC9GL92Z:-NPJVFuV-ZfYzQ-REDHm:b-nk40s) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L49)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I'm talking about this function: https://github.com/hongkai-dai/ManiSkill2/blob/main/mani_skill2/utils/rollout.py#L18 which is used for data generation as well as evaluation
</blockquote></details>

I think we are good on this already. I will file a separate PR (as in the comment above).

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPJsDEmDY5zw2mbmFvm:bdcp4ey) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sounds good. I will do it in my next PR. I think the proposed API (as we discussed in the slack is this):

1. We have the abstract GymAgent class.
2. We have a PlannerAgent class derived from GymAgent class. This PlannerAgent class looks like this
```py
class PlannerAgent(GymAgent):
    # planner is a concrete class, such as RandomShootingPlanner or GradientShootingPlanner
    planner
    def __init__(self, planner):
        self.planner = planner
    def step(self, obs) -> Tuple[torch.Tensor, Dict]:
        return self.planner.step(obs)
```
3. For each of the concrete planner class, such as `RandomShootingPlanner` or `GradientShootingPlanner`, they implement the `step` function. Also each planner will implement the planner-specific function, such as setting up the sampling distribution, setting up the initial value of the action sequence, etc.

Does this sound good to you?
</blockquote></details>

yep that sounds great! Thanks for sketching it out.

One thing is the return value might need to be a `np.ndarray` instead of tensor

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/algorithms/gradient_shooting.py` line 35 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19#-NP3Zw7k20pxl-0x9hyd:-NPJsWp88_jV-ZwqV9QP:b-lyxyfs) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/b0982f99741f94e27ebc3f2b86b1dca0fb177ebe/mani_skill2/algorithms/gradient_shooting.py#L35)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

yep that sounds great! Thanks for sketching it out.

One thing is the return value might need to be a `np.ndarray` instead of tensor
</blockquote></details>

Sounds good. The step function will take this API
```
def step(self, obs, np.ndarray) -> Tuple[np.ndarray, Dict]
```

I will work on this tomorrow (got a bunch of Drake PRs to work on today).

**Pull request merged**
