### PR TITLE
Refactor RollingEnv as described in commit message

### PR DESCRIPTION
**Pull request by blake-wulfe-tri**
1. Change step to return values in accordance with base class
2. Allow for default resetting the environment
3. Return heightmap as obs by default (can change later)
4. Moved heightmap generation functions to rolling env file
5. Reorganize tests and add pytest w/ test script

- - -
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)

### CODE REVIEW

**Review by blake-wulfe-tri — COMMENTED** [review]
+@hongkai-dai 

I originally had this as two commits, but then squashed them.
The first set of changes moves around tests. After the changes you can run all the tests in the repo via `python tools/runtests.py` or (better) `pytest mani_skill2` (pytest is really great; added it as a dep of the repo)
Note the organization of the tests: it's mani_skill2/tests/ and then the same file structure as what's being tests. So for example
`mani_skill2/envs/mpm/rolling_env.py`
`mani_skill2/tests/envs/mpm/test_rolling_env.py`
That's a pretty standard pattern (e.g., https://docs.pytest.org/en/latest/explanation/goodpractices.html#tests-as-part-of-application-code)

The second set of changes change the RollingEnv to adhere to the Env interface so the other data generation code generalizes. Those other changes I'll merge following these.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-:-NNdcR8GAhK2sEkW2lfv:bhpucas)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm:  Thanks for the re-org!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-:-NNdwNAv0EuxgzNY0bOY:b-f0lolx)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNdvnaMEW3uHiMDChKI:bckdvg0) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
> ```Python
> 
>     def reset(self, *args, seed=None, **kwargs):
>         if self._dough_initializer is not None:
> ```

Just curious, if `self._dough_initializer` is not None, does calling super().reset()  reset the initial height map to np.ones((10, 10)) * 0.01? Or does it leave the initial_height_map unchanged?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe-BZJ8nPlRzGYvtqr:b-nn0yah) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious, if `self._dough_initializer` is not None, does calling super().reset()  reset the initial height map to np.ones((10, 10)) * 0.01? Or does it leave the initial_height_map unchanged?
</blockquote></details>

I believe it should leave the heightmap unchanged, so it won't reset it to np.ones. Why do you ask / is it desirable to be able to reset it in that manner?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe-xXK6fZyWhAvAM6B:b-amjskz) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I believe it should leave the heightmap unchanged, so it won't reset it to np.ones. Why do you ask / is it desirable to be able to reset it in that manner?
</blockquote></details>

by that I mean, is there some reason you'd want to be able to reset it to np.ones?

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe0JKj2AqboMS-3onm:b-hzi0i2) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

by that I mean, is there some reason you'd want to be able to reset it to np.ones?
</blockquote></details>

I'm going to do the other PR right now, so will go ahead with merging this PR, but please respond to this anyway so I can take it into account in the future

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe0WOn2Nd75580QRWc:bwl3mc7) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

I'm going to do the other PR right now, so will go ahead with merging this PR, but please respond to this anyway so I can take it into account in the future
</blockquote></details>

actually I'll wait

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe3L2114X0cW7Q84oK:b-chwwiv) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

actually I'll wait
</blockquote></details>

I consider the heightmap as part of the system state. When I see "reset" I am thinking about resetting the system state and observation, which would involve setting the heightmap to some initial value. In the `__init__` function of this class, the heightmap is initialized to np.ones((10, 10)) * 0.01, hence the question.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe8TVJB5mB1_Y5zEkm:b-yx83ww) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I consider the heightmap as part of the system state. When I see "reset" I am thinking about resetting the system state and observation, which would involve setting the heightmap to some initial value. In the `__init__` function of this class, the heightmap is initialized to np.ones((10, 10)) * 0.01, hence the question.
</blockquote></details>

yeah I was thinking that if (i)`self._dough_initializer` is None then the heightmap should just always be np.ones vs (ii) if `self._dough_initializer` is _not_ None then it should be different. So basically reset is a noop in the first case. Does that answer the question or am I missing something?

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNe9RAuApNDerOw4sqS:b1kgdat) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
> (i)self._dough_initializer is None then the heightmap should just always be np.ones

I think with the code in this PR, in the first case, if `self._dough_initializer` is None, then the heightmap is unchanged from its current state, but not reset to np.ones(). Namely if I applied some actions on the dough to change its shape, and then I call reset function, then the dough shape remains the same as before calling the reset function, but its heightmap is not np.ones. Am I getting it right? Basically calling `reset` doesn't reset the dough shape.

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNeCic53HRocr-v7qN4:bh069ij) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> (i)self._dough_initializer is None then the heightmap should just always be np.ones

I think with the code in this PR, in the first case, if `self._dough_initializer` is None, then the heightmap is unchanged from its current state, but not reset to np.ones(). Namely if I applied some actions on the dough to change its shape, and then I call reset function, then the dough shape remains the same as before calling the reset function, but its heightmap is not np.ones. Am I getting it right? Basically calling `reset` doesn't reset the dough shape.
</blockquote></details>

yes that's correct, but I think that's what the behavior was before this PR as well? I guess I could explicitly get that effect by adding something like `flat_dough_generator` that just returns np.ones, which might be more in line with what people would expect the default behavior to be?

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
BTW, I think demo_rolling.py will break since it still calls `data_generation.generate_circular_cone_heightmap`, which is now moved to `rolling_env`.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-:-NNeDzKkAOT8XVWFG2os:b-kebk8i)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @blake-wulfe-tri)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNeCpYz2xLVC1KvPbCY:b-a3rhex) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

yes that's correct, but I think that's what the behavior was before this PR as well? I guess I could explicitly get that effect by adding something like `flat_dough_generator` that just returns np.ones, which might be more in line with what people would expect the default behavior to be?
</blockquote></details>

I like the `flat_dough_generator` idea, then we always have a `self._dough_initializer != None` (with default value being `flat_dough_generator`).

**Review by blake-wulfe-tri — COMMENTED** [review]
nice catch, forgot to run that test since I didn't move it

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-:-NNeFLPs75f9rf_E0GdO:btppyc6)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNeFPva5U205vriEXsj:b-jkkrij) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I like the `flat_dough_generator` idea, then we always have a `self._dough_initializer != None` (with default value being `flat_dough_generator`).
</blockquote></details>

yeah makes sense, I'll go with that!

**Review by blake-wulfe-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`mani_skill2/envs/mpm/rolling_env.py` line 129 at r1](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-NNdvnaLAqCnlflYbfXj:-NNeUihF2mC0_1w5XwoH:bb7xr4x) ([raw file](https://github.com/hongkai-dai/ManiSkill2/blob/cc207a7c720fd33260bb13577bcff62c783c0311/mani_skill2/envs/mpm/rolling_env.py#L129)):*
<details><summary><i>Previously, blake-wulfe-tri wrote…</i></summary><blockquote>

yeah makes sense, I'll go with that!
</blockquote></details>

ok done

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/9#-:-NNeUxSm62stw7hhELin:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @blake-wulfe-tri)

**Pull request merged**
